CREATE TABLE Bank1( bankcode VARCHAR(3),bankname VARCHAR(50),headoffice VARCHAR(50),branches NUMBER);
   
ALTER TABLE Bank1 ADD CONSTRAINT pk_bank PRIMARY KEY (bankcode);

ALTER TABLE Bank1 MODIFY bankname VARCHAR(50) NOT NULL;

ALTER TABLE BANK1 ADD CONSTRAINT CHK_BRANCHES CHECK (BRANCHES > 0);

DESC BANK1

INSERT INTO BANK1 VALUES ('SBT','State Bank','Mumbai',10);
INSERT INTO BANK1 VALUES ('CNA','Canara','Kottayam',8);
INSERT INTO BANK1 VALUES ('FDB','Federal','Ernakulam',7);
INSERT INTO BANK1 VALUES ('SIB','South Indian','New Delhi',4);
INSERT INTO BANK1 VALUES ('BB','Bank of Baroda','Ernakulam',3);

SELECT * FROM BANK1;

CREATE TABLE Branch ( branchid NUMBER, branchname VARCHAR(50) DEFAULT 'New Delhi', bankid VARCHAR(3));

ALTER TABLE Branch ADD CONSTRAINT pk_branch PRIMARY KEY (branchid);

ALTER TABLE BRANCH ADD CONSTRAINT FK_BRANCH_BANK1 FOREIGN KEY (BANKID) REFERENCES BANK1(BANKCODE);

INSERT INTO Branch (branchid,branchname,bankid) VALUES (101, DEFAULT, 'SBT');
INSERT INTO Branch (branchid,branchname,bankid) VALUES (102, 'Kottayam', 'BB');
INSERT INTO BRANCH (BRANCHID,BRANCHNAME,BANKID) VALUES (103, 'Kottayam', 'SIB');
INSERT INTO BRANCH (BRANCHID,BRANCHNAME,BANKID) VALUES (104, DEFAULT, 'FDB');
INSERT INTO Branch (branchid,branchname,bankid) VALUES (105, DEFAULT, 'CNA');

DESC BRANCH
--1
-- Drop the existing foreign key first
ALTER TABLE Branch DROP CONSTRAINT fk_branch_bank1;

-- Recreate the foreign key with ON DELETE CASCADE
ALTER TABLE BRANCH
ADD CONSTRAINT FK_BRANCH_BANK1 FOREIGN KEY (BANKID)
REFERENCES Bank1(bankcode)
ON DELETE CASCADE;

-- Now delete the bank 'SBT'
DELETE FROM Bank1
WHERE BANKCODE = 'SBT';

SELECT * FROM BANK1;
SELECT * FROM BRANCH;
--2
ALTER TABLE BRANCH DROP CONSTRAINT PK_BRANCH;
--3
CREATE OR REPLACE VIEW BANK_HEADOFFICE AS
SELECT * FROM Bank1
WHERE HEADOFFICE = 'kottayam';

DESC BANK_HEADOFFICE
SELECT * FROM BANK_HEADOFFICE;
--4
CREATE OR REPLACE VIEW bank_branch AS
SELECT B.*
FROM Bank1 b
JOIN BRANCH BR ON B.BANKCODE = BR.BANKID
WHERE br.branchname = 'Kottayam';

DESC BANK_BRANCH
SELECT * FROM BANK_BRANCH;
--5
CREATE OR REPLACE VIEW BANKS_MORE_THAN_5_BRANCHES AS
SELECT * FROM BANK1
WHERE BRANCHES > 5;

DESC BANKS_MORE_THAN_5_BRANCHES
SELECT * FROM BANKS_MORE_THAN_5_BRANCHES;
--6
CREATE OR REPLACE VIEW BANKS_IN_NEWDELHI AS
SELECT * FROM BANK1
WHERE HEADOFFICE = 'New Delhi';

DESC BANKS_IN_NEWDELHI
select * from BANKS_IN_NEWDELHI;